Uncaught Exception: error: terminating connection due to administrator command
    at cn.parseErrorMessage (file:///var/task/node_modules/@neondatabase/serverless/index.mjs:1182:6)
    at cn.handlePacket (file:///var/task/node_modules/@neondatabase/serverless/index.mjs:1143:13)
    at cn.parse (file:///var/task/node_modules/@neondatabase/serverless/index.mjs:1127:36)
    at v.<anonymous> (file:///var/task/node_modules/@neondatabase/serverless/index.mjs:1190:16)
    at v.emit (file:///var/task/node_modules/@neondatabase/serverless/index.mjs:397:12)
    at WebSocket.<anonymous> (file:///var/task/node_modules/@neondatabase/serverless/index.mjs:987:80)
    at callListener (/var/task/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/var/task/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:518:28)
    at Receiver.receiverOnMessage (/var/task/node_modules/ws/lib/websocket.js:1220:20) {
  length: 116,
  severity: 'FATAL',
  code: '57P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '3289',
  routine: 'ProcessInterrupts',
  client: NeonClient {
    _events: [Object: null prototype] { error: [Function (anonymous)] },
    _eventsCount: 1,
    _maxListeners: undefined,
    connectionParameters: ConnectionParameters {
      user: 'neondb_owner',
      database: 'neondb',
      port: 5432,
      host: 'ep-blue-snowflake-a6p3twqk.us-west-2.aws.neon.tech',
      binary: false,
      options: undefined,
      ssl: {},
      client_encoding: '',
      replication: undefined,
      isDomainSocket: false,
      application_name: undefined,
      fallback_application_name: undefined,
      statement_timeout: false,
      lock_timeout: false,
      idle_in_transaction_session_timeout: false,
      query_timeout: false,
      connect_timeout: 0
    },
    user: 'neondb_owner',
    database: 'neondb',
    port: 5432,
    host: 'ep-blue-snowflake-a6p3twqk.us-west-2.aws.neon.tech',
    replication: undefined,
    _Promise: [Function: Promise],
    _types: TypeOverrides { _types: [Object], text: {}, binary: {} },
    _ending: true,
    _connecting: false,
    _connected: true,
    _connectionError: false,
    _queryable: false,
    connection: Connection {
      _events: [Object: null prototype],
      _eventsCount: 22,
      _maxListeners: undefined,
      stream: [Socket],
      _keepAlive: false,
      _keepAliveInitialDelayMillis: 0,
      lastBuffer: false,
      parsedStatements: {},
      ssl: false,
      _ending: true,
      _emitMessage: false,
      _connecting: true
    },
    queryQueue: [],
    binary: false,
    processID: 367279222,
    secretKey: -2081670508,
    ssl: false,
    _connectionTimeoutMillis: 0,
    config: {
      connectionString: 'postgresql://neondb_owner:npg_CH0Wn4dVrLMk@ep-blue-snowflake-a6p3twqk.us-west-2.aws.neon.tech/neondb?sslmode=require',
      max: 10,
      maxUses: Infinity,
      allowExitOnIdle: false,
      maxLifetimeSeconds: 0,
      idleTimeoutMillis: 10000
    },
    _connectionCallback: null,
    release: [Function (anonymous)],
    activeQuery: null,
    readyForQuery: true,
    hasExecuted: true,
    _poolUseCount: 3
  }
}
Node.js process exited with exit status: 129. The logs above can help with debugging the issue.